fix: fixed a DTO response
AlexandreBellas/bling-erp-api pull request #7
Opened 2023-04-06 21:10 UTC by Mauro-Domingues

variação tem 2 tipos de retornos.

```typescript
variacoes: {
    variacao: {
      nome: string,
      codigo: string
    } | {
      nome: string
      estoqueAtual: number,
      depositos?: {
        deposito: {
          id: string;
          nome: string;
          saldo: number;
          desconsiderar: 'S' | 'N';
          saldoVirtual: number;
        };
      }[];
    }
  }[]
  ```
  
sendo para listas:
  ```typescript
variacoes: {
    variacao: {
      nome: string,
      codigo: string
    }
}[]
```

e para produto único (buscando pelo código):
```typescript
variacoes: {
    variacao: {
      nome: string
      estoqueAtual: number,
      depositos?: {
        deposito: {
          id: string;
          nome: string;
          saldo: number;
          desconsiderar: 'S' | 'N';
          saldoVirtual: number;
        };
      }[];
    }
  }[]
  ```

2023-04-24 11:52 UTC, AlexandreBellas commented
para isso, separe em interfaces diferentes em cada caso. assim, fica sugestivo ao programador qual é o retorno esperado em cada situação.

2023-04-24 11:54 UTC, AlexandreBellas requested changes

2023-04-24 11:54 UTC, AlexandreBellas commented on src/entities/products.ts
> +      }[];
para isso, separe em interfaces diferentes em cada caso. assim, fica sugestivo ao programador qual é o retorno esperado em cada situação. exemplo: criar um `IProductFindResponse` para definir que o retorno possui esta parte diferente da anterior.

2023-04-24 11:54 UTC, AlexandreBellas commented on src/entities/products.ts
> +      }[];
desta maneira, na linha 287, ficaria algo assim:
```js
  // ...
  find: new Find<IProductFindResponse, IProductInfos>().find,
  // ...
```

2023-04-28 12:43 UTC, Mauro-Domingues commented on src/entities/products.ts
> +      }[];
Posso fazer isso de três maneiras diferentes.

- 1 Reescrevendo a interface toda

```typescript
interface IFindProductResponse {
  ...props + 104 lines,
}
```

- 2 Construindo um tipo e reassinando a propriedade

```typescript
type IFindProductResponse = Pick<
  IProductResponse,
  Exclude<keyof IProductResponse, 'variacoes'>
> & {
  variacoes: {
    variacao: {
      nome: string;
      estoqueAtual: number;
      depositos?: {
        deposito: {
          id: string;
          nome: string;
          saldo: number;
          desconsiderar: 'S' | 'N';
          saldoVirtual: number;
        };
      }[];
    };
  }[];
};
```

3 - construindo uma interface e reescrevendo o valor

```typescript
export interface IProductFindResponse
  extends Pick<IProductResponse, Exclude<keyof IProductResponse, 'variacoes'>> {
  variacoes: {
    variacao: {
      nome: string;
      estoqueAtual: number;
      depositos?: {
        deposito: {
          id: string;
          nome: string;
          saldo: number;
          desconsiderar: 'S' | 'N';
          saldoVirtual: number;
        };
      }[];
    };
  }[];
}
```

Na sua opinião, qual seria melhor aceito para manter a padronização do seu projeto?

2023-04-28 21:31 UTC, Mauro-Domingues commented on src/entities/products.ts
> +      }[];
Exclude entre outras tipagens nativas do typescript são sensacionais. Eu estava pra escrever uma lib também, aquelas propriedades despadronizadas, umas em camelCase outras em snake_case estavam me deixando louco.
Ainda bem que achei sua lib, estou integrando uma api de ecommerce com o bling para gerenciar produtos no bling/ ou em um painel consumindo a api e precisava de algumas requisições para sincronizar os produtos entre o bling e o meu banco de dados pois o site da loja consome a api. A propósito parabens pelo projeto, muito bem feito.

2023-05-02 17:17 UTC, AlexandreBellas approved these changes

2023-05-02 17:17 UTC, merged